### ISSUE TITLE
Commenting your code

### ISSUE THREAD

**Issue by peterbooty** [MaxBialick/My-Portfolio#1]
This is not a huge issue but it's good to comment your code. Especially when you're dealing with multiple DIVs, you can miss closing one and it'll break your build. When you start dealing with hundreds lines of code with rows, columns and other markup, it'll slow you down when you have to navigate through all of the closing tags that have no comments.

What I like to do is add a comment like  to let me know the closing tag's associated class name.

**Comment by MaxBialick** [comment]
Added some comments, not sure what the correct format for doing so in html is though.... is adding spaces like I did frowned upon?

**Comment by peterbooty** [comment]
Looks good.

Spaces aren't frowned upon, unless it's after the line, some people get really obsessed about line spacing.
